/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWalletRouteImport } from './routes/app.wallet'
import { Route as AppReviewsRouteImport } from './routes/app.reviews'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppInProgressRouteImport } from './routes/app.in-progress'
import { Route as AppEarningsRouteImport } from './routes/app.earnings'
import { Route as AppCompletedRouteImport } from './routes/app.completed'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppApplicationsRouteImport } from './routes/app.applications'
import { Route as AppAgentRouteImport } from './routes/app.agent'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAcceptedRouteImport } from './routes/app.accepted'
import { Route as AppTasksIndexRouteImport } from './routes/app.tasks.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppTasksNewRouteImport } from './routes/app.tasks.new'
import { Route as AppTasksIdRouteImport } from './routes/app.tasks.$id'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminReportsRouteImport } from './routes/app.admin.reports'
import { Route as AppAdminFinanceRouteImport } from './routes/app.admin.finance'
import { Route as AppTasksIdApplicationsRouteImport } from './routes/app.tasks.$id.applications'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewsRoute = AppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppInProgressRoute = AppInProgressRouteImport.update({
  id: '/in-progress',
  path: '/in-progress',
  getParentRoute: () => AppRoute,
} as any)
const AppEarningsRoute = AppEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AppRoute,
} as any)
const AppCompletedRoute = AppCompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAcceptedRoute = AppAcceptedRouteImport.update({
  id: '/accepted',
  path: '/accepted',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppTasksNewRoute = AppTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIdRoute = AppTasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminReportsRoute = AppAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminFinanceRoute = AppAdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppTasksIdApplicationsRoute = AppTasksIdApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppTasksIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/accepted': typeof AppAcceptedRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/agent': typeof AppAgentRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/chat': typeof AppChatRoute
  '/app/completed': typeof AppCompletedRoute
  '/app/earnings': typeof AppEarningsRoute
  '/app/in-progress': typeof AppInProgressRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reviews': typeof AppReviewsRoute
  '/app/wallet': typeof AppWalletRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/finance': typeof AppAdminFinanceRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/tasks/$id': typeof AppTasksIdRouteWithChildren
  '/app/tasks/new': typeof AppTasksNewRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/tasks/': typeof AppTasksIndexRoute
  '/app/tasks/$id/applications': typeof AppTasksIdApplicationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/accepted': typeof AppAcceptedRoute
  '/app/agent': typeof AppAgentRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/chat': typeof AppChatRoute
  '/app/completed': typeof AppCompletedRoute
  '/app/earnings': typeof AppEarningsRoute
  '/app/in-progress': typeof AppInProgressRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reviews': typeof AppReviewsRoute
  '/app/wallet': typeof AppWalletRoute
  '/app': typeof AppIndexRoute
  '/app/admin/finance': typeof AppAdminFinanceRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/tasks/$id': typeof AppTasksIdRouteWithChildren
  '/app/tasks/new': typeof AppTasksNewRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/tasks': typeof AppTasksIndexRoute
  '/app/tasks/$id/applications': typeof AppTasksIdApplicationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/accepted': typeof AppAcceptedRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/agent': typeof AppAgentRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/chat': typeof AppChatRoute
  '/app/completed': typeof AppCompletedRoute
  '/app/earnings': typeof AppEarningsRoute
  '/app/in-progress': typeof AppInProgressRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reviews': typeof AppReviewsRoute
  '/app/wallet': typeof AppWalletRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/finance': typeof AppAdminFinanceRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/tasks/$id': typeof AppTasksIdRouteWithChildren
  '/app/tasks/new': typeof AppTasksNewRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/tasks/': typeof AppTasksIndexRoute
  '/app/tasks/$id/applications': typeof AppTasksIdApplicationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/app/accepted'
    | '/app/admin'
    | '/app/agent'
    | '/app/applications'
    | '/app/chat'
    | '/app/completed'
    | '/app/earnings'
    | '/app/in-progress'
    | '/app/notifications'
    | '/app/profile'
    | '/app/reviews'
    | '/app/wallet'
    | '/app/'
    | '/app/admin/finance'
    | '/app/admin/reports'
    | '/app/admin/users'
    | '/app/tasks/$id'
    | '/app/tasks/new'
    | '/app/admin/'
    | '/app/tasks/'
    | '/app/tasks/$id/applications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/app/accepted'
    | '/app/agent'
    | '/app/applications'
    | '/app/chat'
    | '/app/completed'
    | '/app/earnings'
    | '/app/in-progress'
    | '/app/notifications'
    | '/app/profile'
    | '/app/reviews'
    | '/app/wallet'
    | '/app'
    | '/app/admin/finance'
    | '/app/admin/reports'
    | '/app/admin/users'
    | '/app/tasks/$id'
    | '/app/tasks/new'
    | '/app/admin'
    | '/app/tasks'
    | '/app/tasks/$id/applications'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/app/accepted'
    | '/app/admin'
    | '/app/agent'
    | '/app/applications'
    | '/app/chat'
    | '/app/completed'
    | '/app/earnings'
    | '/app/in-progress'
    | '/app/notifications'
    | '/app/profile'
    | '/app/reviews'
    | '/app/wallet'
    | '/app/'
    | '/app/admin/finance'
    | '/app/admin/reports'
    | '/app/admin/users'
    | '/app/tasks/$id'
    | '/app/tasks/new'
    | '/app/admin/'
    | '/app/tasks/'
    | '/app/tasks/$id/applications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reviews': {
      id: '/app/reviews'
      path: '/reviews'
      fullPath: '/app/reviews'
      preLoaderRoute: typeof AppReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/in-progress': {
      id: '/app/in-progress'
      path: '/in-progress'
      fullPath: '/app/in-progress'
      preLoaderRoute: typeof AppInProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/earnings': {
      id: '/app/earnings'
      path: '/earnings'
      fullPath: '/app/earnings'
      preLoaderRoute: typeof AppEarningsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/completed': {
      id: '/app/completed'
      path: '/completed'
      fullPath: '/app/completed'
      preLoaderRoute: typeof AppCompletedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applications': {
      id: '/app/applications'
      path: '/applications'
      fullPath: '/app/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agent': {
      id: '/app/agent'
      path: '/agent'
      fullPath: '/app/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accepted': {
      id: '/app/accepted'
      path: '/accepted'
      fullPath: '/app/accepted'
      preLoaderRoute: typeof AppAcceptedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks/': {
      id: '/app/tasks/'
      path: '/tasks'
      fullPath: '/app/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/tasks/new': {
      id: '/app/tasks/new'
      path: '/tasks/new'
      fullPath: '/app/tasks/new'
      preLoaderRoute: typeof AppTasksNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks/$id': {
      id: '/app/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/app/tasks/$id'
      preLoaderRoute: typeof AppTasksIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/reports': {
      id: '/app/admin/reports'
      path: '/reports'
      fullPath: '/app/admin/reports'
      preLoaderRoute: typeof AppAdminReportsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/finance': {
      id: '/app/admin/finance'
      path: '/finance'
      fullPath: '/app/admin/finance'
      preLoaderRoute: typeof AppAdminFinanceRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/tasks/$id/applications': {
      id: '/app/tasks/$id/applications'
      path: '/applications'
      fullPath: '/app/tasks/$id/applications'
      preLoaderRoute: typeof AppTasksIdApplicationsRouteImport
      parentRoute: typeof AppTasksIdRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminFinanceRoute: typeof AppAdminFinanceRoute
  AppAdminReportsRoute: typeof AppAdminReportsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminFinanceRoute: AppAdminFinanceRoute,
  AppAdminReportsRoute: AppAdminReportsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppTasksIdRouteChildren {
  AppTasksIdApplicationsRoute: typeof AppTasksIdApplicationsRoute
}

const AppTasksIdRouteChildren: AppTasksIdRouteChildren = {
  AppTasksIdApplicationsRoute: AppTasksIdApplicationsRoute,
}

const AppTasksIdRouteWithChildren = AppTasksIdRoute._addFileChildren(
  AppTasksIdRouteChildren,
)

interface AppRouteChildren {
  AppAcceptedRoute: typeof AppAcceptedRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAgentRoute: typeof AppAgentRoute
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppChatRoute: typeof AppChatRoute
  AppCompletedRoute: typeof AppCompletedRoute
  AppEarningsRoute: typeof AppEarningsRoute
  AppInProgressRoute: typeof AppInProgressRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReviewsRoute: typeof AppReviewsRoute
  AppWalletRoute: typeof AppWalletRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTasksIdRoute: typeof AppTasksIdRouteWithChildren
  AppTasksNewRoute: typeof AppTasksNewRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcceptedRoute: AppAcceptedRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAgentRoute: AppAgentRoute,
  AppApplicationsRoute: AppApplicationsRoute,
  AppChatRoute: AppChatRoute,
  AppCompletedRoute: AppCompletedRoute,
  AppEarningsRoute: AppEarningsRoute,
  AppInProgressRoute: AppInProgressRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReviewsRoute: AppReviewsRoute,
  AppWalletRoute: AppWalletRoute,
  AppIndexRoute: AppIndexRoute,
  AppTasksIdRoute: AppTasksIdRouteWithChildren,
  AppTasksNewRoute: AppTasksNewRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
